apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: TempoMonolithic
  namespace: observability
spec:
  jaegerui:
    enabled: true
    ingress:
      enabled: true
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
  storage:
    traces:
      backend: memory