- name: Install trivy
  hosts: ci_server
  become: true
  tasks:
  - name: Install trivy
    shell: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin latest
