---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: argocd-operator-group
  namespace: argocd
spec:
  targetNamespaces:
    - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
  namespace: argocd
spec:
  channel: stable
  name: argocd-operator
  source: community-operators
  sourceNamespace: olm
