apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: community-operators
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/operator-framework/community-operators-catalog:latest
  displayName: Community Operators
  publisher: OperatorHub.io
