apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opentelemetry-operator
  namespace: operators
spec:
  channel: stable
  name: opentelemetry-operator
  source: opentelemetry-operator
  sourceNamespace: olm
