apiVersion: v1
kind: ConfigMap
metadata:
  name: user-database-configmap
  namespace: user-service
data:
  POSTGRES_USER: postgres
  POSTGRES_DB: user
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
