- name: Install Operators
  hosts: control_plane
  tasks:
  - name: Install Operator Lifecycle Manager (OLM)
    command: curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.32.0/install.sh | bash -s v0.32.0
    vars:
      msg: "{{ result.stdout }}"
    notify: [show_result]

  - name: Install Prometheus Operator
    command: kubectl create -f https://operatorhub.io/install/prometheus.yaml
    vars:
      msg: "{{ result.stdout }}"
    notify: [show_result]

  - name: Install Opentelemetry Operator
    command: kubectl create -f https://operatorhub.io/install/opentelemetry-operator.yaml
    vars:
      msg: "{{ result.stdout }}"
    notify: [show_result]

  - name: Install Grafana Operator
    command: kubectl create -f https://operatorhub.io/install/grafana-operator.yaml
    vars:
      msg: "{{ result.stdout }}"
    notify: [show_result]

  - name: Install Tempo Operator
    command: kubectl create -f https://operatorhub.io/install/tempo-operator.yaml
    vars:
      msg: "{{ result.stdout }}"
    notify: [show_result]

  - name: Install Elasticsearch (ECK) Operator
    command: kubectl create -f https://operatorhub.io/install/elastic-cloud-eck.yaml
    vars:
      msg: "{{ result.stdout }}"
    notify: [show_result]

  handlers:
    - name: show_result
      debug:
        msg: "{{ msg }}"
