version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./casc.yaml:/var/jenkins_home/casc.yaml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml

volumes:
  jenkins_home:
