apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
    # startegy
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: neerajbabu/user-service:latest
        command: ["/start.prod.sh"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: user-service-configmap
        - secretRef:
            name: user-service-secret
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
