apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
    # startegy
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: neerajbabu/user:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: user-configmap
        - secretRef:
            name: user-secret
