apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: user-service
type: Opaque
data:
  DB_PASS: postgres
stringData:
  JWT_SECRET: django-insecure-ki!ghgqgr2j+=-db%9coiqe5gr6z^2_rb50@ir&!(qe_%tny4&